import { Product } from '@/types/interface';
export type ProductStatus = 'Active' | 'Disabled';
export type ProductTypes = 'Physical' | 'Digital' | 'Service' | 'Subscription';

export const products: Product[] = [
  {
    id: '1',
    name: 'Professional Laptop',
    code: 'LP-PRO-001',
    productType: 'Physical',
    date: '2024-01-15',
    stock: 25,
    price: 1299.99,
    status: 'Active',
    image: '/products/professional-laptop.png',
  },
  {
    id: '2',
    name: 'Cloud Storage Pro',
    code: 'CS-PRO-002',
    productType: 'Subscription',
    date: '2024-02-10',
    stock: 0, // Not applicable for subscriptions
    price: 29.99,
    status: 'Active',
    image: '/products/cloud-storage-pro.png',
  },
  {
    id: '3',
    name: 'Wireless Headphones',
    code: 'WH-BLU-003',
    productType: 'Physical',
    date: '2024-03-05',
    stock: 5,
    price: 199.99,
    status: 'Active',
    image: '/products/wireless-headphones.png',
  },
  {
    id: '4',
    name: 'Design Software License',
    code: 'DS-LIC-004',
    productType: 'Digital',
    date: '2024-01-20',
    stock: 0, // Not applicable for digital products
    price: 599.99,
    status: 'Active',
    image: '/products/design-software-license.png',
  },
  {
    id: '5',
    name: 'Ergonomic Office Chair',
    code: 'EOC-GRY-005',
    productType: 'Physical',
    date: '2024-04-12',
    stock: 0,
    price: 449.99,
    status: 'Disabled',
    image: '/products/office-ergonomic-chair.png',
  },
  {
    id: '6',
    name: 'Wireless Mouse',
    code: 'WM-BLK-006',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 50,
    price: 19.99,
    status: 'Active',
    image: '/products/wireless-mouse.jpg',
  },
  {
    id: '7',
    name: 'Mechanical Keyboard',
    code: 'MK-RGB-007',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 30,
    price: 79.99,
    status: 'Active',
    image: '/products/mechanical-keyboard.jpg',
  },
  {
    id: '8',
    name: '24inch LED Monitor',
    code: 'MON-24LED-008',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 20,
    price: 149.99,
    status: 'Active',
    image: '/products/24inch-LED-monitor.jpg',
  },
  {
    id: '9',
    name: 'Wi-Fi Router',
    code: 'WFR-AX3000-009',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 35,
    price: 89.99,
    status: 'Active',
    image: '/products/wifi-router.png',
  },
  {
    id: '10',
    name: 'Webcam HD 1080p',
    code: 'WBC-HD1080-010',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 50,
    price: 59.99,
    status: 'Active',
    image: '/products/webcam-hd.png',
  },
  {
    id: '11',
    name: 'All-in-One Printer/Scanner',
    code: 'AIO-PS500-011',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 15,
    price: 179.99,
    status: 'Active',
    image: '/products/printer-scanner.png',
  },
  {
    id: '12',
    name: 'Laptop Backpack',
    code: 'LB-BP1500-012',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 40,
    price: 34.99,
    status: 'Active',
    image: '/products/laptop-backpack.png',
  },
  {
    id: '13',
    name: 'USB Flash Drive (64GB)',
    code: 'UFD-064-013',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 50,
    price: 19.99,
    status: 'Active',
    image: '/products/USB-flash-drive-64gb.png',
  },
  {
    id: '14',
    name: 'Portable Bluetooth Speaker',
    code: 'PBS-250-014',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 20,
    price: 49.99,
    status: 'Active',
    image: '/products/portable-bluetooth-speaker.png',
  },
  {
    id: '15',
    name: 'Ergonomic Mouse Pad',
    code: 'EMP-120-015',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 20,
    price: 14.99,
    status: 'Active',
    image: '/products/ergonomic-mouse-pad.png',
  },
  {
    id: '16',
    name: 'Laptop Cooling Pad',
    code: 'LCP-400-016',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 22,
    price: 34.99,
    status: 'Active',
    image: '/products/laptop-cooling-pad.png',
  },
  {
    id: '17',
    name: 'Antivirus Software License',
    code: 'ASL-245-017',
    productType: 'Digital',
    date: '2025-12-29',
    stock: 0,
    price: 29.99,
    status: 'Active',
    image: '/products/antivirus-software-license.png',
  },
  {
    id: '18',
    name: 'Remote IT Support Service',
    code: 'RIT-102-018',
    productType: 'Service',
    date: '2025-12-29',
    stock: 0,
    price: 39.99,
    status: 'Active',
    image: '/products/remote-it-support-service.png',
  },
  {
    id: '19',
    name: 'Ergonomic Laptop Stand',
    code: 'ELS-556-019',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 75,
    price: 34.99,
    status: 'Active',
    image: '/products/ergonomic-laptop-stand.png',
  },
  {
    id: '20',
    name: 'Bluetooth Earbuds',
    code: 'BTE-223-020',
    productType: 'Physical',
    date: '2025-12-29',
    stock: 120,
    price: 20.99,
    status: 'Active',
    image: '/products/bluetooth-earbuds.png',
  },
];

export const productStatuses: ProductStatus[] = ['Active', 'Disabled'];
export const productTypes: ProductTypes[] = [
  'Physical',
  'Digital',
  'Service',
  'Subscription',
];
